/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileUserRouteImport } from './routes/profile/user'
import { Route as AuthSteamRouteImport } from './routes/auth/steam'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminVersionsRouteImport } from './routes/admin/versions'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminAnnouncementsIndexRouteImport } from './routes/admin/announcements/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminAssetsTauntsRouteImport } from './routes/admin/assets/taunts'
import { Route as AdminAssetsStatsRouteImport } from './routes/admin/assets/stats'
import { Route as AdminAssetsRingoutsRouteImport } from './routes/admin/assets/ringouts'
import { Route as AdminAssetsProfileIconsRouteImport } from './routes/admin/assets/profileIcons'
import { Route as AdminAssetsPerksRouteImport } from './routes/admin/assets/perks'
import { Route as AdminAssetsGemsRouteImport } from './routes/admin/assets/gems'
import { Route as AdminAssetsEmotesRouteImport } from './routes/admin/assets/emotes'
import { Route as AdminAssetsCharactersRouteImport } from './routes/admin/assets/characters'
import { Route as AdminAssetsBannersRouteImport } from './routes/admin/assets/banners'
import { Route as AdminAssetsAnnouncerPaksRouteImport } from './routes/admin/assets/announcerPaks'
import { Route as AdminAnnouncementsAnnouncementIdRouteImport } from './routes/admin/announcements/$announcementId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileUserRoute = ProfileUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ProfileRoute,
} as any)
const AuthSteamRoute = AuthSteamRouteImport.update({
  id: '/auth/steam',
  path: '/auth/steam',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVersionsRoute = AdminVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsIndexRoute = AdminAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AdminRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssetsTauntsRoute = AdminAssetsTauntsRouteImport.update({
  id: '/assets/taunts',
  path: '/assets/taunts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsStatsRoute = AdminAssetsStatsRouteImport.update({
  id: '/assets/stats',
  path: '/assets/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsRingoutsRoute = AdminAssetsRingoutsRouteImport.update({
  id: '/assets/ringouts',
  path: '/assets/ringouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsProfileIconsRoute = AdminAssetsProfileIconsRouteImport.update({
  id: '/assets/profileIcons',
  path: '/assets/profileIcons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsPerksRoute = AdminAssetsPerksRouteImport.update({
  id: '/assets/perks',
  path: '/assets/perks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsGemsRoute = AdminAssetsGemsRouteImport.update({
  id: '/assets/gems',
  path: '/assets/gems',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsEmotesRoute = AdminAssetsEmotesRouteImport.update({
  id: '/assets/emotes',
  path: '/assets/emotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsCharactersRoute = AdminAssetsCharactersRouteImport.update({
  id: '/assets/characters',
  path: '/assets/characters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsBannersRoute = AdminAssetsBannersRouteImport.update({
  id: '/assets/banners',
  path: '/assets/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsAnnouncerPaksRoute =
  AdminAssetsAnnouncerPaksRouteImport.update({
    id: '/assets/announcerPaks',
    path: '/assets/announcerPaks',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnnouncementsAnnouncementIdRoute =
  AdminAnnouncementsAnnouncementIdRouteImport.update({
    id: '/announcements/$announcementId',
    path: '/announcements/$announcementId',
    getParentRoute: () => AdminRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/steam': typeof AuthSteamRoute
  '/profile/user': typeof ProfileUserRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/assets/announcerPaks': typeof AdminAssetsAnnouncerPaksRoute
  '/admin/assets/banners': typeof AdminAssetsBannersRoute
  '/admin/assets/characters': typeof AdminAssetsCharactersRoute
  '/admin/assets/emotes': typeof AdminAssetsEmotesRoute
  '/admin/assets/gems': typeof AdminAssetsGemsRoute
  '/admin/assets/perks': typeof AdminAssetsPerksRoute
  '/admin/assets/profileIcons': typeof AdminAssetsProfileIconsRoute
  '/admin/assets/ringouts': typeof AdminAssetsRingoutsRoute
  '/admin/assets/stats': typeof AdminAssetsStatsRoute
  '/admin/assets/taunts': typeof AdminAssetsTauntsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/steam': typeof AuthSteamRoute
  '/profile/user': typeof ProfileUserRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/assets/announcerPaks': typeof AdminAssetsAnnouncerPaksRoute
  '/admin/assets/banners': typeof AdminAssetsBannersRoute
  '/admin/assets/characters': typeof AdminAssetsCharactersRoute
  '/admin/assets/emotes': typeof AdminAssetsEmotesRoute
  '/admin/assets/gems': typeof AdminAssetsGemsRoute
  '/admin/assets/perks': typeof AdminAssetsPerksRoute
  '/admin/assets/profileIcons': typeof AdminAssetsProfileIconsRoute
  '/admin/assets/ringouts': typeof AdminAssetsRingoutsRoute
  '/admin/assets/stats': typeof AdminAssetsStatsRoute
  '/admin/assets/taunts': typeof AdminAssetsTauntsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/steam': typeof AuthSteamRoute
  '/profile/user': typeof ProfileUserRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/assets/announcerPaks': typeof AdminAssetsAnnouncerPaksRoute
  '/admin/assets/banners': typeof AdminAssetsBannersRoute
  '/admin/assets/characters': typeof AdminAssetsCharactersRoute
  '/admin/assets/emotes': typeof AdminAssetsEmotesRoute
  '/admin/assets/gems': typeof AdminAssetsGemsRoute
  '/admin/assets/perks': typeof AdminAssetsPerksRoute
  '/admin/assets/profileIcons': typeof AdminAssetsProfileIconsRoute
  '/admin/assets/ringouts': typeof AdminAssetsRingoutsRoute
  '/admin/assets/stats': typeof AdminAssetsStatsRoute
  '/admin/assets/taunts': typeof AdminAssetsTauntsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/admin/accounts'
    | '/admin/versions'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/steam'
    | '/profile/user'
    | '/admin/'
    | '/profile/'
    | '/admin/announcements/$announcementId'
    | '/admin/assets/announcerPaks'
    | '/admin/assets/banners'
    | '/admin/assets/characters'
    | '/admin/assets/emotes'
    | '/admin/assets/gems'
    | '/admin/assets/perks'
    | '/admin/assets/profileIcons'
    | '/admin/assets/ringouts'
    | '/admin/assets/stats'
    | '/admin/assets/taunts'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/announcements'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/accounts'
    | '/admin/versions'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/steam'
    | '/profile/user'
    | '/admin'
    | '/profile'
    | '/admin/announcements/$announcementId'
    | '/admin/assets/announcerPaks'
    | '/admin/assets/banners'
    | '/admin/assets/characters'
    | '/admin/assets/emotes'
    | '/admin/assets/gems'
    | '/admin/assets/perks'
    | '/admin/assets/profileIcons'
    | '/admin/assets/ringouts'
    | '/admin/assets/stats'
    | '/admin/assets/taunts'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/announcements'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/admin/accounts'
    | '/admin/versions'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/steam'
    | '/profile/user'
    | '/admin/'
    | '/profile/'
    | '/admin/announcements/$announcementId'
    | '/admin/assets/announcerPaks'
    | '/admin/assets/banners'
    | '/admin/assets/characters'
    | '/admin/assets/emotes'
    | '/admin/assets/gems'
    | '/admin/assets/perks'
    | '/admin/assets/profileIcons'
    | '/admin/assets/ringouts'
    | '/admin/assets/stats'
    | '/admin/assets/taunts'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/announcements/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSteamRoute: typeof AuthSteamRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/user': {
      id: '/profile/user'
      path: '/user'
      fullPath: '/profile/user'
      preLoaderRoute: typeof ProfileUserRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/auth/steam': {
      id: '/auth/steam'
      path: '/auth/steam'
      fullPath: '/auth/steam'
      preLoaderRoute: typeof AuthSteamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/versions': {
      id: '/admin/versions'
      path: '/versions'
      fullPath: '/admin/versions'
      preLoaderRoute: typeof AdminVersionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/': {
      id: '/admin/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assets/taunts': {
      id: '/admin/assets/taunts'
      path: '/assets/taunts'
      fullPath: '/admin/assets/taunts'
      preLoaderRoute: typeof AdminAssetsTauntsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/stats': {
      id: '/admin/assets/stats'
      path: '/assets/stats'
      fullPath: '/admin/assets/stats'
      preLoaderRoute: typeof AdminAssetsStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/ringouts': {
      id: '/admin/assets/ringouts'
      path: '/assets/ringouts'
      fullPath: '/admin/assets/ringouts'
      preLoaderRoute: typeof AdminAssetsRingoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/profileIcons': {
      id: '/admin/assets/profileIcons'
      path: '/assets/profileIcons'
      fullPath: '/admin/assets/profileIcons'
      preLoaderRoute: typeof AdminAssetsProfileIconsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/perks': {
      id: '/admin/assets/perks'
      path: '/assets/perks'
      fullPath: '/admin/assets/perks'
      preLoaderRoute: typeof AdminAssetsPerksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/gems': {
      id: '/admin/assets/gems'
      path: '/assets/gems'
      fullPath: '/admin/assets/gems'
      preLoaderRoute: typeof AdminAssetsGemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/emotes': {
      id: '/admin/assets/emotes'
      path: '/assets/emotes'
      fullPath: '/admin/assets/emotes'
      preLoaderRoute: typeof AdminAssetsEmotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/characters': {
      id: '/admin/assets/characters'
      path: '/assets/characters'
      fullPath: '/admin/assets/characters'
      preLoaderRoute: typeof AdminAssetsCharactersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/banners': {
      id: '/admin/assets/banners'
      path: '/assets/banners'
      fullPath: '/admin/assets/banners'
      preLoaderRoute: typeof AdminAssetsBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets/announcerPaks': {
      id: '/admin/assets/announcerPaks'
      path: '/assets/announcerPaks'
      fullPath: '/admin/assets/announcerPaks'
      preLoaderRoute: typeof AdminAssetsAnnouncerPaksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/$announcementId': {
      id: '/admin/announcements/$announcementId'
      path: '/announcements/$announcementId'
      fullPath: '/admin/announcements/$announcementId'
      preLoaderRoute: typeof AdminAnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminVersionsRoute: typeof AdminVersionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnnouncementsAnnouncementIdRoute: typeof AdminAnnouncementsAnnouncementIdRoute
  AdminAssetsAnnouncerPaksRoute: typeof AdminAssetsAnnouncerPaksRoute
  AdminAssetsBannersRoute: typeof AdminAssetsBannersRoute
  AdminAssetsCharactersRoute: typeof AdminAssetsCharactersRoute
  AdminAssetsEmotesRoute: typeof AdminAssetsEmotesRoute
  AdminAssetsGemsRoute: typeof AdminAssetsGemsRoute
  AdminAssetsPerksRoute: typeof AdminAssetsPerksRoute
  AdminAssetsProfileIconsRoute: typeof AdminAssetsProfileIconsRoute
  AdminAssetsRingoutsRoute: typeof AdminAssetsRingoutsRoute
  AdminAssetsStatsRoute: typeof AdminAssetsStatsRoute
  AdminAssetsTauntsRoute: typeof AdminAssetsTauntsRoute
  AdminAnnouncementsIndexRoute: typeof AdminAnnouncementsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminVersionsRoute: AdminVersionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnnouncementsAnnouncementIdRoute: AdminAnnouncementsAnnouncementIdRoute,
  AdminAssetsAnnouncerPaksRoute: AdminAssetsAnnouncerPaksRoute,
  AdminAssetsBannersRoute: AdminAssetsBannersRoute,
  AdminAssetsCharactersRoute: AdminAssetsCharactersRoute,
  AdminAssetsEmotesRoute: AdminAssetsEmotesRoute,
  AdminAssetsGemsRoute: AdminAssetsGemsRoute,
  AdminAssetsPerksRoute: AdminAssetsPerksRoute,
  AdminAssetsProfileIconsRoute: AdminAssetsProfileIconsRoute,
  AdminAssetsRingoutsRoute: AdminAssetsRingoutsRoute,
  AdminAssetsStatsRoute: AdminAssetsStatsRoute,
  AdminAssetsTauntsRoute: AdminAssetsTauntsRoute,
  AdminAnnouncementsIndexRoute: AdminAnnouncementsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfileRouteChildren {
  ProfileUserRoute: typeof ProfileUserRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserRoute: ProfileUserRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSteamRoute: AuthSteamRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
