import { StatusCodes } from "http-status-codes";
import { Account, accountModel } from "../database/Account";
import { MVSRequests } from "../interfaces/requests_types";
import { MVSResponses } from "../interfaces/responses_types";
import { Request, Response } from "express";
import serverConfiguration from "../config/serverConfiguration";
import * as jwt from "jsonwebtoken";
import env from "../env/env";
import { Player, playerModel } from "../database/Player";
import { IdToString } from "../utils/objectId";
import { MapToRecord } from "../utils/mapToRecord";

export async function handleAccess(
  req: Request<{}, MVSResponses.Access_RESPONSE, MVSRequests.Access_REQUEST, {}>,
  res: Response<MVSResponses.Access_RESPONSE>,
) {
  // let steamTicket = Buffer.from(req.body.auth.steam, "hex");
  // let appSteamTicket = parseAppTicket(steamTicket);

  // if (appSteamTicket == null) {
  //   res.sendStatus(StatusCodes.BAD_REQUEST);
  //   return;
  // }

  const appSteamTicket = { steamID: "123" };

  const now = new Date();

  const jwtToken = jwt.sign(
    {
      steam: appSteamTicket.steamID,
    },
    env.JWT_SECRET,
  );

  const updatedAccount = await accountModel.findOneAndUpdate(
    {
      "identity.alternate.steam.id": appSteamTicket.steamID,
    },
    {
      $set: {
        updated_at: now,
        connections: [
          {
            id: jwtToken,
            start_time: now,
            last_used: now,
            realtime_start_time: 0,
            realtime_end_time: 0,
            metadata: "`\u00010\bPlatform0\u0002PC",
            status: {
              environment: {},
              current_environment: true,
            },
          },
        ],
      },
    },
    {
      new: true,
      upsert: false,
    },
  );

  if (updatedAccount == null) {
    // We should verify we can do this as it could crash the client
    res.sendStatus(StatusCodes.INTERNAL_SERVER_ERROR);
    return;
  }

  const player = await playerModel.findOne({ account_id: updatedAccount._id });

  if (player == null) {
    res.sendStatus(StatusCodes.INTERNAL_SERVER_ERROR);
    return;
  }

  const responseJson: MVSResponses.Access_RESPONSE = {
    token: jwtToken,
    in_queue: false,
    configuration: serverConfiguration,
    account: updatedAccount.toJSON<IdToString<Account>>(),
    profile: player.toJSON<MapToRecord<Player>>(),
    notifications: player.notifications,
    achievements: [],
    maintenance: null,
    wb_network: {
      network_token: "gg",
    },
  };

  // Example of response
  // There is no need to store all fields in the database ( like the configuration field) just the ones that contain player data. The rest can be configured elsewhere
  // The T0dos need implementation like the token field needs to be generated by the server
  // const response: MVSResponses.Access_RESPONSE = {
  //   // TODO access token
  //   token: jwtToken,
  //   in_queue: false,
  //   configuration: serverConfiguration,
  //   achievements: [],
  //   account: accountObj,
  //   // {
  //   //   updated_at: accountDoc.updated_at,
  //   //   created_at: accountDoc.created_at,
  //   //   deleted: accountDoc.deleted,
  //   //   orphaned: false,
  //   //   orphaned_reason: null,
  //   //   public_id: accountDoc.public_id,
  //   //   identity: {
  //   //     alternate: {
  //   //       steam: [accountDoc.identity.alternate.steam!],
  //   //       wb_network: [accountDoc.identity.alternate.wb_network!],
  //   //     },
  //   //     avatar: "https://s3.amazonaws.com/wb-agora-hydra-ugc-dokken/identicons/identicon.584.png",
  //   //     current_platform: "steam",
  //   //     default_username: accountDoc.identity.default_username,
  //   //     is_cross_platform: false,
  //   //     personal_data: {},
  //   //     platforms: ["steam"],
  //   //     username: accountDoc.identity.username,
  //   //     // TODO usernames
  //   //     usernames: [
  //   //       {
  //   //         auth: "hydra",
  //   //         username: "dark-wild-grass-voice-yrpu2",
  //   //       },
  //   //       {
  //   //         auth: "steam",
  //   //         username: accountDoc.identity.username,
  //   //       },
  //   //       {
  //   //         auth: "wb_network",
  //   //         username: accountDoc.identity.username,
  //   //       },
  //   //     ],
  //   //   },
  //   //   email_verification: {
  //   //     state: "unverified",
  //   //   },
  //   //   opt_ins: {
  //   //     wbplay_optin: false,
  //   //   },
  //   //   auth: {
  //   //     wb_network: [
  //   //       {
  //   //         created_at: new Date().toISOString(),
  //   //         id: "pafd8d7950aa1484ea791d06662fa75ce",
  //   //       },
  //   //     ],
  //   //   },
  //   //   wb_account: {
  //   //     completed: true,
  //   //     age_category: "adult",
  //   //     email_verified: false,
  //   //   },
  //   //   external_accounts: {},
  //   //   privacy_levels: {
  //   //     presence: {
  //   //       state: "default",
  //   //     },
  //   //     clan: {
  //   //       invitation: "default",
  //   //     },
  //   //     match: {
  //   //       invitation: "default",
  //   //     },
  //   //     relationship: {
  //   //       follow: "default",
  //   //     },
  //   //   },
  //   //   points: 0,
  //   //   state: "normal",
  //   //   restriction_status: {},
  //   //   wbplay_data_synced: false,
  //   //   wbplay_identity: null,
  //   //   state_data: {},
  //   //   locale: accountDoc.locale,
  //   //   data: {
  //   //     EULAAcceptTimestamp: 1674508690,
  //   //     EULAAcceptVersion: 5,
  //   //     LastLoginPlatform: "EPlatform::PC",
  //   //     LastPlayedCharacterSlug: "character_C018",
  //   //   },
  //   //   // TODO Server Data
  //   //   server_data: {
  //   //     LastLogoutTime: "2023-03-14T17:44:29.198Z",
  //   //     RestedXP: 300,
  //   //     ProfileIcon: {
  //   //       Slug: "profile_icon_default",
  //   //       AssetPath: "/Game/Panda_Main/Blueprints/Rewards/ProfileIcons/ProfileIcon_Default.ProfileIcon_Default",
  //   //     },
  //   //     LastLoginTime: "Tue Mar 14 2023 00:14:29 GMT+0000 (Coordinated Universal Time)",
  //   //     AntiCheatServerKick: 0,
  //   //     OpenBeta: true,
  //   //     LastLoginPlatform: "PC",
  //   //     LastWeeklyRefresh: "2025-03-11T12:00:00.000Z",
  //   //     LastDailyRefresh: "2025-03-13T12:00:00.000Z",
  //   //     Transforms: {
  //   //       GoldStatTracker: true,
  //   //       OpenBetaFreebies: true,
  //   //       BannerKnightSlugFixed: true,
  //   //       UpgradeWarMakeGood_8_5_2024: "2024-08-07T01:07:34.000Z",
  //   //       Season2CharactersInMasterCalculated: true,
  //   //       Season3PrestigeFix: true,
  //   //       CharacterCurrencyRoundUp: "2024-11-12T19:37:33.000Z",
  //   //       MmrSeason4: true,
  //   //       Season4FighterRoadPromo: true,
  //   //       Season4Promo: true,
  //   //       Season4FixRolloverRp: true,
  //   //       ShaggySkinMakeGoodS4: "2024-11-15T23:28:01.000Z",
  //   //       SeasonFourAcademiaMakeGood: "2024-12-13T15:39:16.000Z",
  //   //       SeasonFourAcademiaMakeGoodScoreGranted: 0,
  //   //       Season4RankedRewardCatchup: true,
  //   //       FixRankedCharactersInGold: true,
  //   //     },
  //   //     RetroactiveRiftBattlepassPayoutTime: "2024-06-24T16:24:37.000Z",
  //   //     LastRefreshSeason: "Season:SeasonFive",
  //   //     LastKnownDebugDelta: 0,
  //   //     LastRefreshBattlepassEvent: "evt_battlepass_season_five",
  //   //   },
  //   //   server_owner_data: {},
  //   //   id: accountDoc.id,
  //   //   // TODO connections
  //   //   connections: [
  //   //     {
  //   //       id: "V2wvUvGjnf0Ma23VCEJXFZHDPewZ8FdaYjXGvpqsdzxMHk9BvyPLMTymAOM6WDqW3J4Vek/x3v2yVbxo5r+VbkOpzsk9pVW5zj/0bxOaYgMXPCe4opBb2LY7twuGq4cHh4B7uer44UVxHP/VjzQbHGqEa8BzzdjMrZn3rPGl0H5S9sOkokqiEw==",
  //   //       start_time: MVSTime(new Date()),
  //   //       last_used: MVSTime(new Date()),
  //   //       metadata: "`\u00010\bPlatform0\u0002PC",
  //   //       realtime_start_time: 0,
  //   //       realtime_end_time: 0,
  //   //       status: {
  //   //         environment: {
  //   //           id: "620d88aae6bbaf409686b6fc",
  //   //         },
  //   //         current_environment: true,
  //   //       },
  //   //     },
  //   //   ],
  //   //   presence_state: 1,
  //   //   presence: "online",
  //   // },
  //   profile: {
  //     updated_at: "2025-03-14T03:16:26.000Z",
  //     account_id: accountObj.id,
  //     created_at: "2023-01-23T21:17:48.000Z",
  //     last_login: "2025-03-14T03:16:25.000Z",
  //     points: null,
  //     data: {
  //       IsChildAccount: false,
  //       PerkPreferences: {
  //         // TODO : Character Perk Prefs
  //         Characters: {} as any,
  //       },
  //       HasCompletedFirstMatch: true,
  //       HasCompletedFTUE: true,
  //       MostRecentlyViewedCurrentRiftSeason: "Season:SeasonFour",
  //     },
  //     server_data: {
  //       // Interesting
  //       debug_all_unlocked: 1,
  //       Level: 1,
  //       CurrentXP: 0,
  //       loss_streak: 0,
  //       MatchConfig: {
  //         MultiqueueConfigs: [
  //           {
  //             QueueType: "Unranked",
  //             Context: "Matchmade",
  //             TeamStyle: "Duos",
  //             GameModeAlias: "Versus",
  //           },
  //         ],
  //       },
  //       BattlepassID: "63cef9c6609607a8deb2c31d",
  //       // TODO : Stat trackers
  //       stat_trackers: {
  //         HighestDamageDealt: 656,
  //         TotalRingoutLeader: 22,
  //         TotalRingouts: 13439,
  //         TotalWins: 3129,
  //         character_highest_damage_dealt: {
  //           character_arya: 18,
  //           character_superman: 18,
  //           character_shaggy: 459,
  //           character_Jason: 656,
  //           character_C018: 167,
  //           character_c16: 310,
  //           character_wonder_woman: 524,
  //         },
  //         character_ringouts: {
  //           character_arya: 3,
  //           character_superman: 3,
  //           character_Jason: 13368,
  //           character_C018: 3,
  //           character_shaggy: 37,
  //           character_c16: 3,
  //           character_wonder_woman: 22,
  //         },
  //         character_total_damage_dealt: {
  //           character_arya: 41,
  //           character_superman: 60,
  //           character_shaggy: 3694.185760498047,
  //           character_Jason: 1407299.925918579,
  //           character_C018: 295,
  //           character_c16: 310,
  //           character_wonder_woman: 2925,
  //         },
  //         character_wins: {
  //           character_arya: 2,
  //           character_superman: 1,
  //           character_finn: 4,
  //           character_C018: 3,
  //           character_tom_and_jerry: 1,
  //           character_shaggy: 58,
  //           character_Jason: 3053,
  //           character_c16: 1,
  //           character_wonder_woman: 6,
  //         },
  //         TotalAttacksDodged: 46195,
  //         Valentines2023Currency: 5200,
  //         character_matches: {
  //           character_shaggy: 66,
  //           character_BananaGuard: 1,
  //           character_Jason: 5608,
  //           character_C018: 2,
  //           character_c16: 1,
  //           character_wonder_woman: 8,
  //         },
  //         season1: {
  //           HighestDamageDealt: 131.25,
  //           TotalWins: 2,
  //           character_highest_damage_dealt: {
  //             character_shaggy: 131.25,
  //           },
  //           character_matches: {
  //             character_shaggy: 2,
  //             character_BananaGuard: 1,
  //           },
  //           character_total_damage_dealt: {
  //             character_shaggy: 199.18576049804688,
  //           },
  //           character_wins: {
  //             character_shaggy: 2,
  //           },
  //         },
  //         OpenBetaGold: 350,
  //         season2: {
  //           HighestDamageDealt: 546.0574951171875,
  //           TotalAttacksDodged: 19596,
  //           TotalRingouts: 5774,
  //           TotalWins: 1349,
  //           character_highest_damage_dealt: {
  //             character_Jason: 546.0574951171875,
  //           },
  //           character_matches: {
  //             character_Jason: 2409,
  //           },
  //           character_ringouts: {
  //             character_Jason: 5774,
  //           },
  //           character_total_damage_dealt: {
  //             character_Jason: 545648.9259185791,
  //           },
  //           character_wins: {
  //             character_Jason: 1349,
  //           },
  //           ranked: {
  //             "1v1": {
  //               Wins: 779,
  //               CharactersInGold: 1,
  //             },
  //             "2v2": {
  //               CharactersInGold: 1,
  //             },
  //           },
  //           TotalRingoutLeader: 12,
  //           TotalAssists: 32,
  //           TotalDoubleRingouts: 6,
  //         },
  //         TotalToastsGiven: 706,
  //         TotalToastsReceived: 706,
  //         TotalAssists: 48,
  //         TotalDoubleRingouts: 18,
  //         season3: {
  //           HighestDamageDealt: 591,
  //           TotalAttacksDodged: 12501,
  //           TotalRingouts: 3957,
  //           TotalWins: 920,
  //           character_highest_damage_dealt: {
  //             character_Jason: 591,
  //           },
  //           character_matches: {
  //             character_Jason: 1600,
  //           },
  //           character_ringouts: {
  //             character_Jason: 3957,
  //           },
  //           character_total_damage_dealt: {
  //             character_Jason: 379634,
  //           },
  //           character_wins: {
  //             character_Jason: 920,
  //           },
  //           ranked: {
  //             "1v1": {
  //               Wins: 404,
  //               CharactersInGold: 1,
  //             },
  //           },
  //           TotalDoubleRingouts: 7,
  //           TotalRingoutLeader: 3,
  //         },
  //         season4: {
  //           HighestDamageDealt: 643,
  //           TotalAttacksDodged: 10418,
  //           TotalRingouts: 2785,
  //           character_highest_damage_dealt: {
  //             character_Jason: 643,
  //             character_C018: 167,
  //           },
  //           character_matches: {
  //             character_Jason: 1217,
  //             character_C018: 2,
  //           },
  //           character_ringouts: {
  //             character_Jason: 2782,
  //             character_C018: 3,
  //           },
  //           character_total_damage_dealt: {
  //             character_Jason: 370542,
  //             character_C018: 295,
  //           },
  //           TotalWins: 599,
  //           character_wins: {
  //             character_Jason: 598,
  //             character_C018: 1,
  //           },
  //           ranked: {
  //             "1v1": {
  //               Wins: 242,
  //               CharactersInGold: 1,
  //             },
  //           },
  //           TotalAssists: 2,
  //           TotalDoubleRingouts: 1,
  //           TotalRingoutLeader: 1,
  //         },
  //         season5: {
  //           ranked: {
  //             "1v1": {
  //               CharactersInGold: 1,
  //               Wins: 80,
  //             },
  //           },
  //           HighestDamageDealt: 656,
  //           TotalAttacksDodged: 3675,
  //           TotalRingouts: 917,
  //           character_highest_damage_dealt: {
  //             character_Jason: 656,
  //             character_shaggy: 459,
  //             character_c16: 310,
  //             character_wonder_woman: 524,
  //           },
  //           character_matches: {
  //             character_Jason: 382,
  //             character_shaggy: 64,
  //             character_c16: 1,
  //             character_wonder_woman: 8,
  //           },
  //           character_ringouts: {
  //             character_Jason: 855,
  //             character_shaggy: 37,
  //             character_c16: 3,
  //             character_wonder_woman: 22,
  //           },
  //           character_total_damage_dealt: {
  //             character_Jason: 111475,
  //             character_shaggy: 3495,
  //             character_c16: 310,
  //             character_wonder_woman: 2925,
  //           },
  //           TotalWins: 249,
  //           character_wins: {
  //             character_Jason: 186,
  //             character_shaggy: 56,
  //             character_c16: 1,
  //             character_wonder_woman: 6,
  //           },
  //           TotalRingoutLeader: 4,
  //           TotalDoubleRingouts: 4,
  //           TotalAssists: 14,
  //         },
  //       },
  //       s2_extension_make_good_boost: 1,
  //       checked_grants: {
  //         s2_extension_make_good_boost: true,
  //       },
  //       ftue: {
  //         current_ftue_step: "eDONE",
  //       },
  //       TotalPrestige: 64460,
  //       OpenBeta: true,
  //       Transforms: {
  //         welcome_back: true,
  //         currency_conversion_errored: {
  //           Version_1: false,
  //           Version_2: false,
  //           Version_3: false,
  //         },
  //       },
  //       HasReceivedBattlepassRewardFromOpenBeta: true,
  //       // TODO : SeasonalData
  //       SeasonalData: {
  //         "Season:SeasonTwo": {
  //           Ranked: {
  //             DataByMode: {
  //               "1v1": {
  //                 BestCharacter: {
  //                   CurrentPoints: 2709,
  //                   MaxPoints: 2745,
  //                   GamesPlayed: 2270,
  //                   SetsPlayed: 1317,
  //                   CharacterSlug: "character_Jason",
  //                   LastUpdateTimestamp: "2024-07-26T04:35:44.000Z",
  //                 },
  //                 DataByCharacter: {
  //                   character_Jason: {
  //                     CurrentPoints: 2709,
  //                     MaxPoints: 2745,
  //                     GamesPlayed: 2270,
  //                     SetsPlayed: 1317,
  //                     Wins: 753,
  //                     Losses: 752,
  //                     DamageDealt: 518935,
  //                     DamageTaken: 670230,
  //                     Ringouts: 5496,
  //                     Deaths: 4941,
  //                     LastUpdateTimestamp: "2024-09-17T05:37:40.000Z",
  //                     LastDecayMs: 0,
  //                   },
  //                 },
  //                 GamesPlayed: 2272,
  //                 LastUpdateTimestamp: "2024-09-17T05:37:40.000Z",
  //                 SetsPlayed: 1318,
  //                 FinalLeaderboardRank: 745,
  //               },
  //               "2v2": {
  //                 BestCharacter: {
  //                   CurrentPoints: 1035,
  //                   MaxPoints: 1047,
  //                   GamesPlayed: 107,
  //                   SetsPlayed: 48,
  //                   CharacterSlug: "character_Jason",
  //                   LastUpdateTimestamp: "2024-08-20T02:02:32.000Z",
  //                 },
  //                 DataByCharacter: {
  //                   character_Jason: {
  //                     CurrentPoints: 1035,
  //                     MaxPoints: 1047,
  //                     GamesPlayed: 107,
  //                     SetsPlayed: 48,
  //                     Wins: 25,
  //                     Losses: 26,
  //                     DamageDealt: 18082,
  //                     DamageTaken: 26826,
  //                     Ringouts: 193,
  //                     Deaths: 177,
  //                     LastUpdateTimestamp: "2024-08-24T16:45:00.000Z",
  //                     LastDecayMs: 0,
  //                   },
  //                 },
  //                 GamesPlayed: 107,
  //                 LastUpdateTimestamp: "2024-08-24T16:45:00.000Z",
  //                 SetsPlayed: 48,
  //                 FinalLeaderboardRank: 37414,
  //               },
  //             },
  //             ClaimedRewards: [
  //               "EC1B6F59453B11272D24DD94189FC209",
  //               "BB3E4B7048C823BE345B8F86CCBCCA84",
  //               "89709B1442BF36DD11BD98BCFB0D4AF1",
  //               "40B4F0174999C47FEAD0CE91419BBC7B",
  //               "B67EDC654607F8583E06978841798205",
  //               "8519085948FD7C75D380A9B4646A2306",
  //               "F2A63E5C406E3D13D9C5BCB0CCBDE371",
  //               "AD47AB5D491ACF00EF52289735A8B493",
  //               "684E91904181C8F3636BE38CF4B0E3C6",
  //               "C8C6CD8140A6E7A30F589CB10E677113",
  //             ],
  //             bEndOfSeasonRewardsGranted: true,
  //           },
  //         },
  //         "Season:SeasonThree": {
  //           Ranked: {
  //             DataByMode: {
  //               "1v1": {
  //                 DataByCharacter: {
  //                   character_Jason: {
  //                     CurrentPoints: 2858,
  //                     MaxPoints: 2929,
  //                     GamesPlayed: 1591,
  //                     SetsPlayed: 672,
  //                     Wins: 404,
  //                     Losses: 403,
  //                     DamageDealt: 376835,
  //                     DamageTaken: 481079,
  //                     Ringouts: 3929,
  //                     Deaths: 3411,
  //                     LastUpdateTimestamp: "2024-11-11T23:10:40.000Z",
  //                     LastDecayMs: 0,
  //                   },
  //                 },
  //                 GamesPlayed: 1591,
  //                 SetsPlayed: 672,
  //                 BestCharacter: {
  //                   CurrentPoints: 2858,
  //                   MaxPoints: 2929,
  //                   GamesPlayed: 1591,
  //                   SetsPlayed: 672,
  //                   CharacterSlug: "character_Jason",
  //                   LastUpdateTimestamp: "2024-09-18T01:39:41.000Z",
  //                 },
  //                 LastUpdateTimestamp: "2024-11-11T23:10:40.000Z",
  //                 FinalLeaderboardRank: 857,
  //               },
  //               "2v2": {
  //                 DataByCharacter: {
  //                   character_Jason: {
  //                     CurrentPoints: 35,
  //                     MaxPoints: 35,
  //                     GamesPlayed: 0,
  //                     SetsPlayed: 0,
  //                     Wins: 0,
  //                     Losses: 0,
  //                     DamageDealt: 0,
  //                     DamageTaken: 0,
  //                     Ringouts: 0,
  //                     Deaths: 0,
  //                     LastUpdateTimestamp: "2024-09-18T01:39:41.000Z",
  //                     LastDecayMs: 0,
  //                   },
  //                 },
  //                 GamesPlayed: 0,
  //                 SetsPlayed: 0,
  //                 BestCharacter: {
  //                   CurrentPoints: 35,
  //                   MaxPoints: 35,
  //                   GamesPlayed: 0,
  //                   SetsPlayed: 1,
  //                   CharacterSlug: "character_Jason",
  //                   LastUpdateTimestamp: "2024-09-18T01:39:41.000Z",
  //                 },
  //                 FinalLeaderboardRank: 129774,
  //               },
  //             },
  //             ClaimedRewards: [
  //               "B67EDC654607F8583E06978841798205",
  //               "F2A63E5C406E3D13D9C5BCB0CCBDE371",
  //               "AD47AB5D491ACF00EF52289735A8B493",
  //               "684E91904181C8F3636BE38CF4B0E3C6",
  //               "C8C6CD8140A6E7A30F589CB10E677113",
  //             ],
  //             bEndOfSeasonRewardsGranted: true,
  //           },
  //         },
  //         "Season:SeasonFour": {
  //           LastLoginDay: "2025-01-31T00:00:00.000Z",
  //           NumDaysLoggedIn: 27,
  //           NumLogins: 45,
  //           Ranked: {
  //             DataByMode: {
  //               "1v1": {
  //                 DataByCharacter: {
  //                   character_Jason: {
  //                     CurrentPoints: 2457,
  //                     MaxPoints: 2605,
  //                     GamesPlayed: 1189,
  //                     SetsPlayed: 493,
  //                     Wins: 238,
  //                     Losses: 239,
  //                     DamageDealt: 361469,
  //                     DamageTaken: 379378,
  //                     Ringouts: 2713,
  //                     Deaths: 2780,
  //                     LastUpdateTimestamp: "2025-01-31T20:44:58.000Z",
  //                     LastDecayMs: 0,
  //                   },
  //                 },
  //                 GamesPlayed: 1189,
  //                 SetsPlayed: 493,
  //                 BestCharacter: {
  //                   CurrentPoints: 2457,
  //                   MaxPoints: 2605,
  //                   GamesPlayed: 1189,
  //                   SetsPlayed: 493,
  //                   CharacterSlug: "character_Jason",
  //                   LastUpdateTimestamp: "2024-11-13T15:47:31.000Z",
  //                 },
  //                 LastUpdateTimestamp: "2025-01-31T20:44:58.000Z",
  //                 FinalLeaderboardRank: 694,
  //               },
  //             },
  //             ClaimedRewards: [
  //               "B67EDC654607F8583E06978841798205",
  //               "F2A63E5C406E3D13D9C5BCB0CCBDE371",
  //               "AD47AB5D491ACF00EF52289735A8B493",
  //               "684E91904181C8F3636BE38CF4B0E3C6",
  //               "C8C6CD8140A6E7A30F589CB10E677113",
  //             ],
  //             bEndOfSeasonRewardsGranted: true,
  //           },
  //         },
  //         "Season:SeasonFive": {
  //           LastLoginDay: "2025-03-14T00:00:00.000Z",
  //           NumDaysLoggedIn: 18,
  //           NumLogins: 176,
  //           Ranked: {
  //             DataByMode: {
  //               "1v1": {
  //                 DataByCharacter: {
  //                   character_Jason: {
  //                     CurrentPoints: 2137,
  //                     MaxPoints: 2179,
  //                     GamesPlayed: 371,
  //                     SetsPlayed: 160,
  //                     Wins: 80,
  //                     Losses: 79,
  //                     DamageDealt: 109764,
  //                     DamageTaken: 120253,
  //                     Ringouts: 837,
  //                     Deaths: 856,
  //                     LastUpdateTimestamp: "2025-03-02T08:15:12.000Z",
  //                     LastDecayMs: 0,
  //                   },
  //                 },
  //                 GamesPlayed: 371,
  //                 SetsPlayed: 160,
  //                 BestCharacter: {
  //                   CurrentPoints: 2137,
  //                   MaxPoints: 2179,
  //                   GamesPlayed: 371,
  //                   SetsPlayed: 160,
  //                   CharacterSlug: "character_Jason",
  //                   LastUpdateTimestamp: "2025-02-08T02:53:45.000Z",
  //                 },
  //                 LastUpdateTimestamp: "2025-03-02T08:15:12.000Z",
  //               },
  //             },
  //             ClaimedRewards: [
  //               "D17B128B40B9A1A73A8602A9D25A1A3A",
  //               "C8C6CD8140A6E7A30F589CB10E677113",
  //               "BB3E4B7048C823BE345B8F86CCBCCA84",
  //               "F2A63E5C406E3D13D9C5BCB0CCBDE371",
  //               "EC1B6F59453B11272D24DD94189FC209",
  //               "0D5B77894611BDDA93E815BCFEE03AE8",
  //               "B67EDC654607F8583E06978841798205",
  //             ],
  //           },
  //         },
  //       },
  //       NumOwnedBaseRosterFighters: 15,
  //       exm_segment_membership: {
  //         exm_global_segments: ["mvs_fighter_affinity_pvp_jason_today", "mvs_hydra_segment_test_true", "mvs_purchaser_status_non_purchaser"],
  //         exm_experiment_segments: [],
  //         exm_experiment_arm_map: {},
  //       },
  //       NumOwnedFighters: 16,
  //     },
  //     server_owner_data: {},
  //     // TODO : Inventory
  //     inventory: {
  //       character_shaggy: {
  //         count: 1,
  //       },
  //       character_BananaGuard: {
  //         count: 1,
  //         created_at: "2024-06-05T21:32:11.000Z",
  //       },
  //       character_Jason: {
  //         count: 1,
  //         created_at: "2024-07-02T20:53:29.000Z",
  //       },
  //       character_c024: {
  //         count: 1,
  //         created_at: "2024-08-24T16:18:33.000Z",
  //       },
  //       character_currency: {
  //         count: 18000,
  //         created_at: null,
  //       },
  //       character_wonder_woman: {
  //         count: 1,
  //         created_at: "2024-11-12T19:38:27.000Z",
  //       },
  //       "battlepass-season-1": {
  //         count: 1,
  //         created_at: "2024-05-30T15:50:02.000Z",
  //       },
  //       character_batman: {
  //         count: 1,
  //         created_at: "2024-11-15T16:40:38.000Z",
  //       },
  //       character_bugs_bunny: {
  //         count: 1,
  //         created_at: "2024-11-15T16:40:51.000Z",
  //       },
  //       character_tom_and_jerry: {
  //         count: 1,
  //         created_at: "2024-11-25T23:01:03.000Z",
  //       },
  //       character_jake: {
  //         count: 1,
  //         created_at: "2024-11-25T23:01:08.000Z",
  //       },
  //       character_garnet: {
  //         count: 1,
  //         created_at: "2024-11-25T23:01:11.000Z",
  //       },
  //       character_finn: {
  //         count: 1,
  //         created_at: "2024-12-06T04:03:57.000Z",
  //       },
  //       skin_c034_s01: {
  //         count: 1,
  //         created_at: "2024-07-05T21:05:46.000Z",
  //       },
  //       character_superman: {
  //         count: 1,
  //         created_at: "2025-01-05T02:52:07.000Z",
  //       },
  //       character_c019: {
  //         count: 1,
  //         created_at: "2025-01-05T02:52:25.000Z",
  //       },
  //       character_c16: {
  //         count: 1,
  //         created_at: "2025-01-22T03:32:47.000Z",
  //       },
  //       character_steven: {
  //         count: 1,
  //         created_at: "2025-01-30T23:12:48.000Z",
  //       },
  //       character_C029: {
  //         count: 1,
  //         created_at: "2025-02-08T02:54:17.000Z",
  //       },
  //       character_C020: {
  //         count: 1,
  //         created_at: "2025-03-10T15:52:09.000Z",
  //       },
  //       character_c038: {
  //         count: 1,
  //         created_at: "2025-03-10T15:55:29.000Z",
  //       },
  //     },
  //     // TODO : matches stats
  //     matches: {
  //       rift_container_one_player: {
  //         win: 2,
  //         loss: 0,
  //         challenge_win: 0,
  //         challenge_loss: 0,
  //         win_streak: 2,
  //         loss_streak: 0,
  //         longest_win_streak: 2,
  //         longest_loss_streak: 0,
  //       },
  //       custom_container_one_player: {
  //         win: 1,
  //         loss: 2,
  //         challenge_win: 0,
  //         challenge_loss: 0,
  //         win_streak: 0,
  //         loss_streak: 1,
  //         longest_win_streak: 1,
  //         longest_loss_streak: 1,
  //       },
  //       custom_container_two_player: {
  //         win: 60,
  //         loss: 36,
  //         challenge_win: 0,
  //         challenge_loss: 0,
  //         win_streak: 0,
  //         loss_streak: 1,
  //         longest_win_streak: 36,
  //         longest_loss_streak: 4,
  //       },
  //       custom_container_one_player_online: {
  //         win: 1,
  //         loss: 14,
  //         challenge_win: 0,
  //         challenge_loss: 0,
  //         win_streak: 0,
  //         loss_streak: 0,
  //         longest_win_streak: 1,
  //         longest_loss_streak: 0,
  //       },
  //       "1v1_container_bot": {
  //         win: 4,
  //         loss: 1,
  //         challenge_win: 0,
  //         challenge_loss: 0,
  //         win_streak: 4,
  //         loss_streak: 0,
  //         longest_win_streak: 4,
  //         longest_loss_streak: 0,
  //       },
  //       "1v1_container": {
  //         win: 3024,
  //         loss: 2518,
  //         challenge_win: 0,
  //         challenge_loss: 0,
  //         win_streak: 0,
  //         loss_streak: 1,
  //         longest_win_streak: 18,
  //         longest_loss_streak: 12,
  //       },
  //       "2v2_container": {
  //         win: 57,
  //         loss: 53,
  //         challenge_win: 0,
  //         challenge_loss: 0,
  //         win_streak: 1,
  //         loss_streak: 0,
  //         longest_win_streak: 6,
  //         longest_loss_streak: 0,
  //       },
  //       arena_container_four_player: {
  //         win: 1,
  //         loss: 1,
  //         challenge_win: 0,
  //         challenge_loss: 0,
  //         win_streak: 0,
  //         loss_streak: 1,
  //         longest_win_streak: 1,
  //         longest_loss_streak: 1,
  //       },
  //       ffa_container: {
  //         win: 2,
  //         loss: 3,
  //         challenge_win: 0,
  //         challenge_loss: 0,
  //         win_streak: 0,
  //         loss_streak: 2,
  //         longest_win_streak: 2,
  //         longest_loss_streak: 2,
  //       },
  //     },
  //     cross_match_results: {},
  //     notifications: {},
  //     // TODO : aggregates battlepasses
  //     aggregates: {
  //       "s1-battlepass-score": {
  //         type_class: "current_value",
  //         value: 6000,
  //       },
  //       "s3-battlepass-score": {
  //         type_class: "current_value",
  //         value: 133729,
  //       },
  //       "s4-battlepass-score": {
  //         type_class: "current_value",
  //         value: 50430,
  //       },
  //       "fighter-road-xp": {
  //         type_class: "current_value",
  //         value: 212724,
  //       },
  //     },
  //     calculations: {},
  //     files: [],
  //     user_segments: [
  //       "test-user-segment",
  //       "percentmaintenance",
  //       "issteam",
  //       "owns_batman",
  //       "owns_bugs_bunny",
  //       "owns_superman",
  //       "owns_garnet",
  //       "owns_finn_the_human",
  //       "owns_tom_and_jerry",
  //       "owns_jake_the_dog",
  //       "owns_steven_universe",
  //       "owns_lebron_james",
  //       "returning_user_open_beta",
  //       "owns_morty",
  //       "owns_rick",
  //       "owns_wonder_woman",
  //       "owns_jason",
  //       "bp-score-over-100",
  //       "owns_battlepass_s1",
  //       "does_not_own_the_joker",
  //       "does_not_own_agent_smith_or_decompiled",
  //       "owns_beetlejuice",
  //       "owns_banana_guard",
  //       "s3-battlepass-tier-greater-or-equal-to-60",
  //       "experimentation-mvs_hydra_segment_test_true",
  //       "experimentation-mvs_purchaser_status_non_purchaser",
  //       "experimentation-mvs_fighter_affinity_pvp_jason_today",
  //       "powerpuff_dynamo_defense_pack_carousel_conditions",
  //       "lost_samurai_carousel_conditions",
  //       "nubia_early_access_usd_pinned_carousel_conditions",
  //       "nubia_early_access_carousel_condition",
  //       "not-new-player",
  //       "raven_early_access_usd_pinned_carousel_conditions",
  //       "owns-16-fighters-gleamium-bundle-condition",
  //       "fighter_store_eligible",
  //       "raven-early-access-carousel-condition",
  //       "fighter_currency_premium",
  //       "marceline_early_access_carousel_condition",
  //       "marceline_early-access_usd_pinned_carousel_conditions",
  //       "bp_s4_5_conditions",
  //       "bp_s4_conditions",
  //     ],
  //     random_distribution: 0.25115115419482414,
  //     // TODO : profile id
  //     id: "63cef97ced0619f458cfac90",
  //   },
  //   notifications: [],
  //   maintenance: null,
  //   wb_network: {
  //     // TODO : network token
  //     network_token: "I+MPokHx/JkCFmuHpcEiapVMN1511Y/i3ekWkkR0C5aFmiuwvQWNhlAtW7bUzyobBcV0CkIdnXE+oFHMwDtsiVUCWGDDyzF3aFTGazhvwb8=",
  //   },
  // };

  res.json(responseJson as any);
}
