name: On Push
on: push
jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install packages
        run: npm install --only=dev
      - name: check style
        run: npm run check-style
